name: Release package on NPM

on:
  release:
    types: [created]

jobs:
  publish-npm:
    if: startsWith(github.event.release.tag_name, 'flowbite-qwik@')
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: https://registry.npmjs.org
      - run: pnpm --filter flowbite-qwik install --frozen-lockfile
      - run: pnpm --filter flowbite-qwik build
      - run: pnpm --filter flowbite-qwik publish --provenance --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPMJS_TOKEN}}
